## This workflow will build a Java project with Maven
## For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#
#name: Test Java
#
#on:
#  push:
#    branches: [ master, develop ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#    env:
#      MYSQL_HOST: ${{ secrets.MYSQL_HOST}}
#      USER_DB: ${{ secrets.USER_DB }}
#      PASS_DB: ${{ secrets.PASS_DB }}
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 11
#      uses: actions/setup-java@v2
#      with:
#        java-version: '11'
#        distribution: 'adopt'
#    - name: Run the Maven verify phase
#      run: mvn --batch-mode --update-snapshots verify
